### ISSUE TITLE
0.109 I/O alert

### ISSUE THREAD

**Issue by sagitt** [tuxuser/hassio-addons#12]
![Schermata 2020-04-29 alle 18 24 03](https://user-images.githubusercontent.com/169086/80620779-b78c7200-8a46-11ea-9668-0b1485314be1.png)

**Comment by sagitt** [comment]
will be fixed?

**Comment by blazem** [comment]
Also getting this error.

**Comment by finalbillybong** [comment]
I am also getting this error.

**Comment by JOHLC** [comment]
Also getting the same error
Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:105
First occurred: 6:37:06 PM (954 occurrences)
Last logged: 7:56:20 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for xboxone doing I/O at custom_components/xboxone/media_player.py, line 94: return requests.get(full_url, *args, **kwargs)

**Comment by blair287** [comment]
This error has been here for months i guess this integration is dead.....
