### ISSUE TITLE
auth after every restart

### ISSUE THREAD

**Issue by blazem** [tuxuser/hassio-addons#15]
Apologies if I have missed it somewhre in the documentation, but is there a setting to have the server automatically authenticate after every reboot / restart?

I am currently having to manually authenticate via http://localhost:5557/auth/oauth after every reboot / restart.

Is there an auto authenticate setting?

**Comment by blazem** [comment]
**FIXED**

I have sorted this by creating a REST sensor and having this activated on Home Assistant boot

**Comment by whatdaybob** [comment]
@blazem can you please share the rest sensor you used as you maybe have fixed an issue I have struggled with for almost a year, if you dont mind.

**Comment by blazem** [comment]
@whatdaybob here mate this is in my config.yaml - works so far for me:

![image](https://user-images.githubusercontent.com/11291673/83342011-04ad7d80-a33e-11ea-8014-dba48b0383e6.png)

This is the automation for booting:

![image](https://user-images.githubusercontent.com/11291673/83342075-ebf19780-a33e-11ea-8870-48b5ef215be9.png)

![image](https://user-images.githubusercontent.com/11291673/83342036-5f46d980-a33e-11ea-8d58-a781a24b4124.png)

 Only problem I am having with this smartglass integration is the state not always correct (says ON when it should be PLAYING)

**Comment by whatdaybob** [comment]
@blazem thanks for that, i use rest for loads of sensors but never looked into the commands. I will see if using this fixes my refresh token issue.

**Comment by blazem** [comment]
@whatdaybob no worries. I hope it works for you!
