### ISSUE TITLE
Erorr auth and others

### ISSUE THREAD

**Issue by sagitt** [tuxuser/hassio-addons#16]
After oauth:

{"message":"Unhandled authentication error: 'DisplayClaims'","success":false,"two_factor_required":false}

![Schermata 2020-05-30 alle 15 06 51](https://user-images.githubusercontent.com/169086/83329016-44fdf480-a287-11ea-961a-d82005f1924f.png)
![Schermata 2020-05-30 alle 15 06 57](https://user-images.githubusercontent.com/169086/83329018-462f2180-a287-11ea-84b5-6f1d7686d808.png)
![Schermata 2020-05-30 alle 15 07 05](https://user-images.githubusercontent.com/169086/83329019-47604e80-a287-11ea-8bd2-52b4513de193.png)

**Comment by blazem** [comment]
I think a lot of these recent errors that remain Open are related to the new HA code required? I hope there is an update to this XboxOne integration very soon!!
