### ISSUE TITLE
Console is not alive? (solved, posting as help for others)

### ISSUE THREAD

**Issue by GsynthChris** [tuxuser/hassio-addons#18]
I figured this out just before posting but I am sure it could be helpful for someone so I want to get the info out there anyway.

"Hello, I've been having some trouble with this integration for a few days now. I can't get any of my rest commands to work anymore. I reinstalled the integration and in the process migrated to this branch of it instead of hunterjm's which was when my issue started. For instance, if I try to run "http://192.168.29.5:5557/device/FD00CFAxxxxxxxxx/media/play_pause" I get  {"message":"Console FD00CFAxxxxxxxxx is not alive","success":false}
(idk if my console number is a security issue so I edited it lol)"

I went to http://192.168.29.5:5557/device and looked at the list of options and found one that said device/<live ID>/connect so I plugged in http://192.168.29.5:5557/device/FD00CFAxxxxxxxxx/connect and I got a "success" message and after that my rest commands seem to be working. hahaha.

I had already tried the auth/oauth link and tried logging out and logging back in again. I also tried uninstalling the addon again and reinstalling it again.

I've been working on this for days and JUST as I am giving up and reaching out for help I thought I'd dig around one last time and there is was. 

Hope this helps someone! THANKS FOR KEEPING THIS INTEGRATION ALIVE!!!

**Comment by GsynthChris** [comment]
Well... Now i'm not sure if something is up. I have had to redo this connect thing three times today... hhmmmm

**Comment by batfasturd** [comment]
I wonder if this will fix my issue with the media_status not showing correctly. Most of the time it shows null after I wake my console up until I do a full Xbox reboot. It's really annoying, I wish Microsoft would just allow direct API read access.

**Comment by blair287** [comment]
Mine will not respond to the connect command says nothing.

If I go to /devices I can see it but says disconnected.

I came from the old rest server too and not been able to make it work anymore :(

Started working now.

But sometimes gets stuck at unknown.
