### ISSUE TITLE
Hassio addon

### ISSUE THREAD

**Issue by staraxis** [tuxuser/hassio-addons#2]
I successfully added the add-on url in the Home Assistant Supervisor section but no addons are displaying. I've hit refresh numerous times. 
Getting this error:
`20-03-01 04:34:53 ERROR (MainThread) [hassio.store.git] Can't clone https://github.com/OpenXbox/xboxone-home-assistant/tree/master/hassio repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/OpenXbox/xboxone-home-assistant/tree/master/hassio /data/addons/git/7e19de3a
  stderr: 'Cloning into '/data/addons/git/7e19de3a'...
fatal: repository 'https://github.com/OpenXbox/xboxone-home-assistant/tree/master/hassio/' not found
'.
20-03-01 04:34:53 ERROR (MainThread) [hassio.store] Can't load from repository https://github.com/OpenXbox/xboxone-home-assistant/tree/master/hassio`

Let me know if there's anything else you need.

**Comment by tuxuser** [comment]
It looks like you might have added the repo URL in the supervisor tab in the wrong format.

1. Remove the failing entry / URL.
1. Restart home assistant.
1. Add the exact following URL: `https://github.com/OpenXbox/xboxone-home-assistant`.

**Comment by chadmccune** [comment]
I'm having the same problem, and I re-added the repo to make sure I had exactly above:

0-03-01 05:28:47 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/41cba666/hassio/config.json: required key not provided @ data['options']. Got None
required key not provided @ data['schema']. Got None

**Comment by tuxuser** [comment]
Thanks for the report, please try again now.
You might have to re-add the repository too.

**Comment by chadmccune** [comment]
Repo added, addon shows up now, but now get this error:

20-03-01 05:37:12 ERROR (SyncWorker_16) [hassio.docker.interface] Can't install OpenXbox/hassio-armv7-xboxone:2.0.3 -> 400 Client Error: Bad Request ("invalid reference format: repository name must be lowercase").

**Comment by tuxuser** [comment]
*push* (please try again)

**Comment by chadmccune** [comment]
Had to remove and readd the repo again, but now its working

**Comment by tuxuser** [comment]
@chadmccune 
great!

@staraxis 
Does it work for you too?

**Comment by staraxis** [comment]
The addon shows up now. Great work thanks!
