### ISSUE TITLE
Home Assistant warning

### ISSUE THREAD

**Issue by tigattack** [tuxuser/hassio-addons#22]
I'm running the latest beta of Home Assistant (0.113.0b3).  
The following error is shown in the log:

> Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for xboxone doing I/O at custom_components/xboxone/media_player.py, line 94: return requests.get(full_url, *args, **kwargs)

**Comment by psychocircus98** [comment]
Same here. I also find that when my Home Assistant (0.113.2) turns the Xbox off I get "Update of media_player.xbox_one is taking over 10 seconds" appearing in my logs.

For reference here's the other error seen:
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for xboxone doing I/O at custom_components/xboxone/media_player.py, line 94: return requests.get(full_url, *args, **kwargs)

**Comment by blair287** [comment]
Same issue

**Comment by P1zz1** [comment]
Same issue

**Comment by tuxuser** [comment]
Tracked in #16
