### ISSUE TITLE
Multiple xbox logins

### ISSUE THREAD

**Issue by chadmccune** [tuxuser/hassio-addons#3]
In my household, we have 3 different xbox consoles with 3 different gold memberships, can we authenticate to all 3 with all 3 accounts?

**Comment by tuxuser** [comment]
Sorry, that's currently not possible.

Protocol-wise: &#x2714;
In the current level of implementation: &#x274C;

If somebody has a proposal how that specific API could look without destroying the comfort for people who only have a single account, feel free to jump in.

Note: API proposal for both, the [xbox-rest-server](https://github.com/OpenXbox/xbox-smartglass-core-python) and the home assistant integration!

**Comment by hunterjm** [comment]
Is it still possible to authenticate anonymously?  If so, that'd be my recommendation.  This way it won't kick the current logged in user off when sending commands.
