### ISSUE TITLE
Suffering for HA folks will be over soon...

### ISSUE THREAD

**Issue by tuxuser** [tuxuser/hassio-addons#31]
Check out https://github.com/home-assistant/core/pull/41697

**Comment by Celedhrim** [comment]
Not very good for me.

I use this on my lan to detect if xbox is on or off , and with an automation I switch input on my home cinema

It work like a charm except the warning for async io in logs.

This new intégration in 0.117 need a link with a cloud account and subscription. :(
5$/month just to know if my xbox is on or not ... :)

More : my hass setup  must work without internet ( actually it does) , the cloud intégration means that if I loose internet , of if the hass cloud service is down , my automation is down :(

For me it's not great  ! :D

**Comment by tuxuser** [comment]
https://community.home-assistant.io/t/hass-io-add-on-xbox-one/63750/366

**Comment by Celedhrim** [comment]
Thx to point this ! :)

Ths is a sad news but no choice , we will see when this will happen.

Anyway thx for all your work past / present / futur for support of xbox on hass , It's much than appreciate :)

**Comment by tuxuser** [comment]
Thanks ;)

Just realized: Home Assistant is 0.117 was released few days ago!

So suffering for most is over now^^
