### ISSUE TITLE
Migrating from Eric's to this one

### ISSUE THREAD

**Issue by clsferguson** [tuxuser/hassio-addons#5]
https://github.com/ericleb010/hassio-addons

Hey, I was hoping to migrate to this version of the addon since it is a newer version. So I removed Eric's addon and installed this one. I can login to the oauth and see my devices on the network. I really didn't have to change my config entry. But now hassio doesn't see the media players as online at all.

Thoughts?

**Comment by tuxuser** [comment]
Did you use the matching custom component or are you still on the _old_ one by ericleb010 ?

The process got changed in the term that hassio-addon and custom component need to be installed separately.

**Comment by clsferguson** [comment]
that seems to have fixed it. thanks. I deleted the custom component and added yours from HACS.
