### ISSUE TITLE
Invalid xbox-smartglass-core version

### ISSUE THREAD

**Issue by MadD0c** [tuxuser/hassio-addons#6]
I recently installed this integration using hacs. I also installed the xbox-smartglass-core-python for the rest server. 

On restart I have recieved the following error:
Invalid xbox-smartglass-core version: 1.2.1. Required: 1.1.2

The integration version installed is: 24e5308
The smartglass server: 1.2.1
My Home Assistant version: 0.105.5 (Docker on Raspberry Pi 3B)

I can see the xbox but am unable to do any form of control.

Please advise

**Comment by whatdaybob** [comment]
I to receive the same error
``` log
2020-04-13 02:29:07 ERROR (SyncWorker_8) [custom_components.xboxone.media_player] Invalid xbox-smartglass-core version: 1.2.2. Required: 1.1.2
```
Happy to test anything.

**Comment by tuxuser** [comment]
Could you please test the custom_component in `develop` branch - replace existing with the ones from the repo.

https://github.com/OpenXbox/xboxone-home-assistant/tree/develop/custom_components/xboxone

**Comment by whatdaybob** [comment]
Perfect, that has fixed it! appreciate the hard work!

**Comment by tuxuser** [comment]
Thanks for your report, gonna merge to master
