### ISSUE TITLE
Games do not show as the background of the media player card

### ISSUE THREAD

**Issue by mikekreisher** [tuxuser/hassio-addons#8]
When a game is the active source for the component, the media player card just shows a gray background and the friendly name of the entity. Clicking on the 3 vertical dots shows the active source correctly identified as the game and a thumbnail of the game being played. When an app is the active source, the media player's background changes color, displays the app's name, and shows an image of the app. Is it possible for this same behavior to happen when a game is active? For example, the media card will say the game's name and change the background to match the image used as the thumbnail, which is I believe the entity_picture asset?

**Comment by mastermc0** [comment]
I will create a pull request for the way I fixed this for the maintainer to review it's fairly simple but will let the package maintainer check if I've missed its impact on some other code.

**Comment by tuxuser** [comment]
Should be fixed, thanks to PR #10 by @mastermc0

**Comment by mikekreisher** [comment]
Thank for the quick fix, this looks great!
